### PR TITLE
Assign section/course users frontend

### PR DESCRIPTION
**Pull request by msladwig**
-Created pages for assigning users to sections and courses.
-Created view classes for assigning sections and courses, implemented with just GET to display the page.
-Added pages to urls.py
-Updated sections and courses to have a button for both assigning users and deleting the course.
-Updated courses page with field for viewing assigned instructor.

### CODE REVIEW

**Comment by msladwig** [comment]
This is just the frontend skeleton for the implementation of this sprint's PBIs; I expect these to change quite a bit as we implement.

**Comment by MWHunter** [comment]
I've added some backend code to this pull request to make it more like what it should be.

Not all backend code is complete for this though so someone will have to implement that.  Also I didn't bother making the frontend look good, I was just trying to give the methods and stuff for how we will actually display information and send requests to the server

**Review by SohamNandi — APPROVED** [review]
New pages work fine. Looks good.

**Comment by msladwig** [comment]
> I've added some backend code to this pull request to make it more like what it should be.
> 
> Not all backend code is complete for this though so someone will have to implement that. Also I didn't bother making the frontend look good, I was just trying to give the methods and stuff for how we will actually display information and send requests to the server

Updated the frontend for this and a tweaked the views to be able to pull correct user information

**Pull request merged**
